### ISSUE TITLE
정답 데이터셋 만들기

### ISSUE THREAD

**Issue by MaryYoungae** [plus1250-project/joba-Data#13]
### 1. 산업군별 기업리스트 파일 생성
* Dart API를 통해 기업별 업종코드 리스트 생성 
* **기업별 업종코드 리스트 &  Main Category의 업종코드**를 이용하여 **산업군별 기업리스트** 생성
  * Main Category의 업종코드 : 한국표준산업분류를 이용하여 취업관련 산업군으로 분류 (완료)

### 2. 기사 Text 파일 생성
* 기사 크롤링을 통해 생성된 파일(title,url,text,press,date)에서 기사 text만 추출

### 3. NER 모델 API를 사용을 위한 기사 샘플링
* NER모델 요청 제한 : 5000회, 1회 10000자 미만
* 9500자 미만의 기사 중 4500개의 기사만 랜덤으로 추출

### 4. 기업명 추출
* 샘플링된 기사를 NER모델을 활용하여 기업명 추출

### 5. 산업군 라벨링
* **기업명이 추출된 기사 & 산업군별 기업리스트**를 이용하여 정답 데이터셋 생성

**Comment by evememine** [comment]
### 기업별 업종 코드 리스트에 중복 확인 
기업별 업종 코드 리스트에 기업 이름이 중복되는 상황이 발생
- 상장 폐지된 기업까지 포함된 것을 확인 
### 해결 방안
- 기업의 stock_code를 조회하여 폐지된 기업인 경우 삭제처리 
- 삭제 처리 기업 리스트
```
정다운			00659435,(주)정다운,정다운,224090,1011
엔케이맥스		01212383,(주)엔케이맥스,엔케이맥스,262760,21210
핸디소프트		00231521,(주)핸디소프트,핸디소프트,032380,58221
포인트엔지니어링		00580180,(주)포인트엔지니어링,포인트엔지니어링,176560,259
카이노스메드		00843830,(주)카이노스메드,카이노스메드,220250,70113
고려시멘트		00102821,고려시멘트(주),고려시멘트,003660,23311
하나은행			00130897,(주)하나은행,하나은행,002860,64121
국민은행			00386937,(주)국민은행,국민은행,060000,64121
에스와이			00151252,에스와이(주),에스와이,004530,1080
한국비엔씨		01051339,(주)한국비엔씨,한국비엔씨,226610,271
엠에프엠코리아		00814810,엠에프엠코리아(주),엠에프엠코리아,251960,143
패션플랫폼		01010572,패션플랫폼(주),패션플랫폼,256090,14112
케이엠제약		01090921,케이엠제약(주),케이엠제약,237720,20422
자비스			00921475,(주)자비스,자비스,230400,271
씨아이에스		00822572,씨아이에스(주),씨아이에스,144630,292
두산건설(2) 		00115852,두산건설(주),두산건설,002950,41221
			00102760,두산건설(주),두산건설,011160,41112
세화피앤씨		00461690,(주)세화피앤씨,세화피앤씨,085980,20423
알루코			00139418,알루코(주),알루코,021570,26294
알로이스			01194892,(주)알로이스,알로이스,271400,26421
나무기술 		00925453,나무기술 주식회사,나무기술,167380,582
판타지오			00991012,(주)판타지오,판타지오,187770,73901
소프트캠프		00656340,소프트캠프(주),소프트캠프,210610,58222
원바이오젠		01138993,주식회사 원바이오젠,원바이오젠,278380,21300          
우리금융지주		00375302,우리금융지주(주),우리금융지주,053000,64992                       
에스에이티		00563147,(주)에스에이티,에스에이티,158300,29271                        
삼성물산			00126229,삼성물산(주),삼성물산,000830,467                         
본느			01119217,주식회사 본느,본느,242420,204                           
휴럼			01148909,주식회사 휴럼,휴럼,284420,107                           
인산가			00408336,(주)인산가,인산가,062580,107                          
줌인터넷			01128622,줌인터넷(주),줌인터넷,239340,631			                         
신성이엔지		00686068,(주)신성이엔지,신성이엔지,104110,292 	                       
미래에셋증권		00311030,미래에셋증권(주),미래에셋증권,037620,66121                       
아이엘사이언스		01181940,주식회사 아이엘사이언스,아이엘사이언스,122050,28422		                      
SK			00144155,SK(주),SK,003600,64992                           
```

**Comment by dongbin1234** [comment]
## 훈련데이터 셋 라벨링
### 기준
**1. 표시**
* 삭제 : 0
* 통과 : 1<br>

**보류내용은 산업군명, 산업군코드 변경후 1 표시

**2. 삭제 기준**
* 내용이 한문장 이하인 사진 설명
* 숫자 위주의 주식 기사
* 여러 산업군의 기업 혼재
* 행사 관련된 기사 (단, 한 기업이 주최한 기사는 제외)
* 산업군과 관련없는 정치 기사

**3. 통과 기준**
* 여러 기업이 나오지만 같은 산업군일 경우
* 산업군에 관련된 행사
* 재무제표 기사
* 기업에 사업 설명이 포함된 광고
* 카테고리 기타로 분류된 기사
* 기업의 중요도가 높은 환경 기사

**4. 보류 기준**(산업군명, 산업군코드 수정)
* 모델이 분류한 산업군과는 다른 산업군의 기사일 경우
### 삭제 카테고리
1. 전기/가스업
2. 섬유/의류<br>

**목표 데이터량: 산업군별 200개씩
