### ISSUE TITLE
Spark와 Mysql 연결 테스트 에러

### ISSUE THREAD

**Issue by MaryYoungae** [plus1250-project/joba-Data#4]
### 에러 에메지
```
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
```

### 문의 사항
알려주신 계정과 비밀번호로 접속 시 에러가 발생합니다.
권한 설정 한번만 체크 부탁 드립니다~

**Comment by jeremyjkim** [comment]
확인했습니다.
ip 지정해서 권한 설정하겠습니다;)

**Comment by MaryYoungae** [comment]
보내 주신 계정ID와 비밀번호 입력시 계속 에러가 뜹니다..
확인 부탁드려요~

**Comment by jeremyjkim** [comment]
아... 비밀번호를 다르게 설정했었네요.. 
다시 수정했습니다~ 확인해주세요~

**Comment by MaryYoungae** [comment]
연결되었습니다! 감사합니다~
