### ISSUE TITLE
알수 없는 계정의 흔적 발생

### ISSUE THREAD

**Issue by MaryYoungae** [plus1250-project/joba-Data#5]
### 문제 화면
![에러](https://user-images.githubusercontent.com/97429679/173869227-4023ebd0-12bf-4a14-a2ba-ce5dc6e93c1a.PNG)

### 문제 원인
* AWS의 보안 인바운드 규칙에서 모든 TCP에 대한 모든 IP로 규칙을 설정되어 있어, 하둡-스파크 인스턴스에 대한 악성 외부 요청으로 판단

### 해결 방안
* 보안 인바운드 규칙을 모든 TCP에 대한 내IP로만 지정
* 내IP는 현재 시점에서 개인 PC가 사용하고 있는 public ip로 장소를 변경하여 사용시 설정한 IP 재설정 필요

### 체크사항
* **하둡-스파크 이용이 필요한 팀원은 보안 그룹에 규칙을 추가해야 하므로 문의 부탁드립니다.**

**Comment by evememine** [comment]
하둡-스파크 사용이 필요합니다 !! 이슈 해결에 참여하겠습니다~~

**Comment by MaryYoungae** [comment]
@evememine  처리 완료 되었습니다.

**Comment by jeremyjkim** [comment]
제 ip 추가해주세요~

**Comment by dongbin1234** [comment]
저도 하둡-스파크 이용이 필요합니다.

**Comment by MaryYoungae** [comment]
@jonnygim @dblee0410  처리 완료 되었습니다.
